aws_region        = "us-east-1"
availability_zone = "us-east-1d"
instance_type     = "t2.large"
subnet_id         = "subnet-0d2642da77bbfe744"
security_group_id = "sg-0a18f708db91ef96f"
key_name          = "shankaraws"
vol_size          = "80"
vol_type          = "gp3"
